// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-09-16 23:10:08.9246778 +0200 CEST m=+5.833373701
// using data from
// https://wiki.teamfortress.com/wiki/demoman_responses
package responses

var demomanResponses = []Response{
	
	{
		Class: DEMOMAN,
		Response: "How's that feel, ya blockhead?",
		AudioFile: "https://wiki.teamfortress.com/w/images/3/34/Demoman_specialcompleted04.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with a Secondary Weapon",
		Condition: "",
	},
	
	{
		Class: DEMOMAN,
		Response: "Ya great lactating wet nurse!",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b4/Demoman_taunts02.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with a Secondary Weapon",
		Condition: "",
	},
	
	{
		Class: DEMOMAN,
		Response: "Don't fret, boyo. I'll be gentle!",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/44/Demoman_taunts04.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with a Secondary Weapon",
		Condition: "",
	},
	
	{
		Class: DEMOMAN,
		Response: "Oh, they're goin' ta have to glue you back together...IN HELL!",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/8c/Demoman_taunts08.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with a Secondary Weapon",
		Condition: "",
	},
	
}
