// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-09-16 23:10:12.5052566 +0200 CEST m=+9.413952501
// using data from
// https://wiki.teamfortress.com/wiki/engineer_responses
package responses

var engineerResponses = []Response{
	
	{
		Class: ENGINEER,
		Response: "Whoooowee! Makin' bacon!",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/db/Engineer_specialcompleted05.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with any weapon (except Gunslinger)",
		Condition: "",
	},
	
	{
		Class: ENGINEER,
		Response: "How'd that plan turn out for ya, dummy?",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b9/Engineer_specialcompleted10.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with any weapon (except Gunslinger)",
		Condition: "",
	},
	
	{
		Class: ENGINEER,
		Response: "That's what ya get!",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/76/Engineer_specialcompleted11.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with any weapon (except Gunslinger)",
		Condition: "",
	},
	
}
