// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-09-16 23:10:10.7927212 +0200 CEST m=+7.701417101
// using data from
// https://wiki.teamfortress.com/wiki/heavy_responses
package responses

var heavyResponses = []Response{
	
	{
		Class: HEAVY,
		Response: "Cry some more!",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/03/Heavy_specialcompleted09.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with a Primary Weapon",
		Condition: "",
	},
	
	{
		Class: HEAVY,
		Response: "(Mimicking a baby crying) Weeeeeeeeh! Waaaaaaaahh!",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/6c/Heavy_specialcompleted10.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with a Primary Weapon",
		Condition: "",
	},
	
	{
		Class: HEAVY,
		Response: "Maniacal laugh",
		AudioFile: "https://wiki.teamfortress.com/w/images/2/22/Heavy_specialcompleted11.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with a Primary Weapon",
		Condition: "",
	},
	
	{
		Class: HEAVY,
		Response: "I'm coming for you!",
		AudioFile: "https://wiki.teamfortress.com/w/images/2/2d/Heavy_taunts04.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with a Primary Weapon",
		Condition: "",
	},
	
	{
		Class: HEAVY,
		Response: "Keep crying, baby!",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/9f/Heavy_taunts05.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with a Primary Weapon",
		Condition: "",
	},
	
	{
		Class: HEAVY,
		Response: "All of you are babies!",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/75/Heavy_taunts11.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with a Primary Weapon",
		Condition: "",
	},
	
}
