// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-09-16 23:10:14.2728927 +0200 CEST m=+11.181588601
// using data from
// https://wiki.teamfortress.com/wiki/medic_responses
package responses

var medicResponses = []Response{
	
	{
		Class: MEDIC,
		Response: "Eins, zwei, drei... Ugh, I do not think ve brought enough body bags. (Translation: One, two, three...)",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/a1/Medic_taunts02.wav",
		Context: "After killing more than 1 Enemy in 20 seconds with a Primary or Melee weapon",
		Condition: "",
	},
	
	{
		Class: MEDIC,
		Response: "Haha! Vat a bloodbath!",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/f0/Medic_specialcompleted12.wav",
		Context: "After killing more than 1 Enemy in 20 seconds with a Primary or Melee weapon",
		Condition: "",
	},
	
}
