// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-09-18 17:07:46.4269018 +0200 CEST m=+2.063178501
// using data from
// https://wiki.teamfortress.com/wiki/medic_responses
package responses

import "github.com/MattIzSpooky/tf2.rest/class"

var medicResponses = []Response{
	
	{
		Class: 		class.MEDIC,
		Response:  "Eins, zwei, drei... Ugh, I do not think ve brought enough body bags. (Translation: One, two, three...)",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/a1/Medic_taunts02.wav",
		Type: 	   "Kill-related",
		SubType:   "",
		Context:   "After killing more than 1 Enemy in 20 seconds with a Primary or Melee weapon",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Haha! Vat a bloodbath!",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/f0/Medic_specialcompleted12.wav",
		Type: 	   "Kill-related",
		SubType:   "",
		Context:   "After killing more than 1 Enemy in 20 seconds with a Primary or Melee weapon",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zat vas doktor-assisted homicide!",
		AudioFile: "https://wiki.teamfortress.com/w/images/3/38/Medic_specialcompleted09.wav",
		Type: 	   "Kill-related",
		SubType:   "",
		Context:   "After killing more than 3 Enemies in 20 seconds with a Primary or Melee weapon",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ze healing is not as revarding as ze hurting.",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/99/Medic_specialcompleted02.wav",
		Type: 	   "Kill-related",
		SubType:   "",
		Context:   "After killing more than 3 Enemies in 20 seconds with a Primary or Melee weapon",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Oops! Zat vas not Medizin! (literally medicine)",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/f7/Medic_specialcompleted10.wav",
		Type: 	   "Kill-related",
		SubType:   "",
		Context:   "After killing more than 3 Enemies in 20 seconds with a Primary or Melee weapon",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Can you feel ze Schadenfreude? (Schadenfreude is a German compound noun referring to the taking of pleasure in the pain of others.)",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/e7/Medic_specialcompleted11.wav",
		Type: 	   "Kill-related",
		SubType:   "",
		Context:   "After killing more than 3 Enemies in 20 seconds with a Primary or Melee weapon",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "(Quietly) Did zat sting? (Louder) SAW-ry!",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/9a/Medic_specialcompleted01.wav",
		Type: 	   "Kill-related",
		SubType:   "",
		Context:   "Melee Kill",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Danke, Kamerad! (German for Thanks, Comrade!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/15/Medic_specialcompleted-assistedkill01.wav",
		Type: 	   "Kill-related",
		SubType:   "",
		Context:   "Kill assist",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ve did it, Kamerad!",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/10/Medic_specialcompleted-assistedkill02.wav",
		Type: 	   "Kill-related",
		SubType:   "",
		Context:   "Kill assist",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Would you like a second opinion?  You are also ugly! [See The Second Opinion]",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/5f/Medic_taunts14.wav",
		Type: 	   "Domination-related",
		SubType:   "",
		Context:   "Domination",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Come over here. I promise I will heal you!",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/53/Medic_taunts12.wav",
		Type: 	   "Domination-related",
		SubType:   "",
		Context:   "Domination",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Long laugh (Schadenfreude)",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/93/Medic_laughlong01.wav",
		Type: 	   "Domination-related",
		SubType:   "",
		Context:   "Domination",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Long laugh 2",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/8b/Medic_laughlong02.wav",
		Type: 	   "Domination-related",
		SubType:   "",
		Context:   "Domination",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Happy laugh",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/66/Medic_laughhappy01.wav",
		Type: 	   "Domination-related",
		SubType:   "",
		Context:   "Domination",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Happy laugh 2",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/77/Medic_laughhappy02.wav",
		Type: 	   "Domination-related",
		SubType:   "",
		Context:   "Domination",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Happy laugh 3",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/d5/Medic_laughhappy03.wav",
		Type: 	   "Domination-related",
		SubType:   "",
		Context:   "Domination",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Evil laugh",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/df/Medic_laughevil02.wav",
		Type: 	   "Domination-related",
		SubType:   "",
		Context:   "Domination",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Evil laugh 2",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/4d/Medic_laughevil05.wav",
		Type: 	   "Domination-related",
		SubType:   "",
		Context:   "Domination",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Short laugh",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/4d/Medic_laughshort03.wav",
		Type: 	   "Domination-related",
		SubType:   "",
		Context:   "Domination",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Stupendous!",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/f8/Medic_goodjob02.wav",
		Type: 	   "Domination-related",
		SubType:   "",
		Context:   "Revenge Kill",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Schweinhunds.",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/7f/Medic_negativevocalization02.wav",
		Type: 	   "Domination-related",
		SubType:   "",
		Context:   "Revenge Kill",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Schweinhunds!",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/44/Medic_negativevocalization06.wav",
		Type: 	   "Domination-related",
		SubType:   "",
		Context:   "Revenge Kill",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Dummkopfs!",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/4c/Medic_negativevocalization07.wav",
		Type: 	   "Domination-related",
		SubType:   "",
		Context:   "Revenge Kill",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Raus, Raus! (Translation: Out, out!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/6f/Medic_battlecry01.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Forward!",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/f6/Medic_battlecry02.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Heil, us! (Translation: Hail, us!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/df/Medic_battlecry03.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Hyaaaa!",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/c2/Medic_battlecry04.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Horrido! (German Hunting/War cry)",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/85/Medic_battlecry05.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Gesundheit! (Translation: To your health!/Bless you [Sarcastic])",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b2/Medic_battlecry06.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Fess... (Translation: So tired...)",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/85/Medic_jeers01.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Sudden Death",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Iz zere a point to your lives?",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/9a/Medic_jeers02.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Sudden Death",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "My skill is VASTED on zis team!",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/d0/Medic_jeers03.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Sudden Death",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "DUMMKOPFS!(Translation: Fools!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/ff/Medic_jeers04.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Sudden Death",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Booo!",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/56/Medic_jeers05.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Sudden Death",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "You are trying my patience!",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/e5/Medic_jeers06.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Sudden Death",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Teeeeeeam! (Likely a reference to Colonel Klink's Schuuuulllllttttz! from Hogan's Heroes.)",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/fa/Medic_jeers07.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Sudden Death",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Velcome to the 've lose vonce again'-fest.",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/68/Medic_jeers08.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Sudden Death",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ach, was ist los? (Translation: Gah, what's the matter?)",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/83/Medic_jeers09.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Sudden Death",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "From now on, losing is verboten! (Translation: Forbidden)",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/e1/Medic_jeers11.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Sudden Death",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Schweinhunds! (Translation: Pig-dogs!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/fc/Medic_jeers12.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Sudden Death",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zis... is unacceptable!",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/49/Medic_autodejectedtie01.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Stalemate",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Anyvun still alive has let me down!",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/eb/Medic_autodejectedtie02.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Stalemate",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Dawww...",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b1/Medic_autodejectedtie03.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Stalemate",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Schweinhunds! (Again, the grammatically correct version is Schweinehunde!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/8f/Medic_autodejectedtie04.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Stalemate",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Awwww...",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/69/Medic_autodejectedtie05.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Stalemate",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Aiii...",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/10/Medic_autodejectedtie06.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Stalemate",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Hawww!",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b5/Medic_autodejectedtie07.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Stalemate",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Fire, fire, fire!",
		AudioFile: "https://wiki.teamfortress.com/w/images/3/34/Medic_autoonfire01.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Set on Fire",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Fiiiiire!",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/0b/Medic_autoonfire02.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Set on Fire",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I am on fire!",
		AudioFile: "https://wiki.teamfortress.com/w/images/2/2a/Medic_autoonfire03.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Set on Fire",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Everyone, I am on fire!",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/7b/Medic_autoonfire04.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Set on Fire",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I am melting! (A reference to the Wicked Witch of the West from The Wizard of Oz.)",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/4d/Medic_autoonfire05.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Set on Fire",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "*Dying scream*",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/6b/Medic_paincrticialdeath01.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "On Death",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "*Dying scream*",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/7e/Medic_paincrticialdeath02.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "On Death",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "*Dying scream*",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/a2/Medic_paincrticialdeath03.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "On Death",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "*Dying scream*",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/0c/Medic_paincrticialdeath04.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "On Death",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Good to go!",
		AudioFile: "https://wiki.teamfortress.com/w/images/3/32/Medic_specialcompleted07.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Destruction(s)",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Did ze Fräuleins have zeir Mittelschmerz? (Literal translation: Did the ladies have their menstrual cramps?)",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/f0/Medic_specialcompleted08.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Destruction(s)",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Raaah...",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/88/Medic_negativevocalization04.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Hit by Jarate, Mad Milk, Mutated Milk, Self-Aware Beauty Mark, or the Gas Passer",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "MNAAH!",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b8/Medic_negativevocalization05.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Hit by Jarate, Mad Milk, Mutated Milk, Self-Aware Beauty Mark, or the Gas Passer",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Awwww...",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/69/Medic_autodejectedtie05.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Hit by Jarate, Mad Milk, Mutated Milk, Self-Aware Beauty Mark, or the Gas Passer",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Aiii...",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/10/Medic_autodejectedtie06.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Hit by Jarate, Mad Milk, Mutated Milk, Self-Aware Beauty Mark, or the Gas Passer",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Hawww!",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b5/Medic_autodejectedtie07.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Hit by Jarate, Mad Milk, Mutated Milk, Self-Aware Beauty Mark, or the Gas Passer",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Danke, Engineer!",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/8f/Medic_thanksfortheteleporter01.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Teleportation",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Danke, mein (my) hard-hatted friend!",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/c2/Medic_thanksfortheteleporter02.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Teleportation",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zank you, Engineer!",
		AudioFile: "https://wiki.teamfortress.com/w/images/3/3c/Medic_thanksfortheteleporter03.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Teleportation",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zank you, Herr Doktor!",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/1a/Medic_thanksfortheheal01.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Healed by Medic",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Danke, Herr Doktor!",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/a2/Medic_thanksfortheheal02.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Healed by Medic",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ze healing is not as rewarding as ze hurting.",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/99/Medic_specialcompleted02.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Under the effects of an ÜberCharge",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ze healing leaves little time for ze hurting.",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/47/Medic_specialcompleted03.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Under the effects of an ÜberCharge",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Good to go!",
		AudioFile: "https://wiki.teamfortress.com/w/images/3/32/Medic_specialcompleted07.wav",
		Type: 	   "Event-related Responses",
		SubType:   "",
		Context:   "Under the effects of an ÜberCharge",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ready to charge!",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/c0/Medic_autochargeready01.wav",
		Type: 	   "Weapon-related",
		SubType:   "",
		Context:   "Upon full ÜberCharge Meter",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I am fully charged.",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/6c/Medic_autochargeready02.wav",
		Type: 	   "Weapon-related",
		SubType:   "",
		Context:   "Upon full ÜberCharge Meter",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I am charged.",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/9f/Medic_autochargeready03.wav",
		Type: 	   "Weapon-related",
		SubType:   "",
		Context:   "Upon full ÜberCharge Meter",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Now go!",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/f6/Medic_specialcompleted04.wav",
		Type: 	   "Weapon-related",
		SubType:   "",
		Context:   "Activating a Medi Gun ÜberCharge",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Get zem. Raus, Raus! (Translation: Get them. Go, Go!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/63/Medic_specialcompleted05.wav",
		Type: 	   "Weapon-related",
		SubType:   "",
		Context:   "Activating a Medi Gun ÜberCharge",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Schnell! Go get zem! (Translation: Hurry! Go get them!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/e7/Medic_specialcompleted06.wav",
		Type: 	   "Weapon-related",
		SubType:   "",
		Context:   "Activating a Medi Gun ÜberCharge",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Auf Wiedersehen, Schweinehunds! (Translation: Goodbye, pig-dogs!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/a1/Medic_taunts09.wav",
		Type: 	   "Weapon-related",
		SubType:   "",
		Context:   "Activating a Kritzkrieg or Quick-Fix ÜberCharge",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Auf wiedersehen, Dummkopfs! (Translation: Goodbye, idiots!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/6d/Medic_taunts03.wav",
		Type: 	   "Weapon-related",
		SubType:   "",
		Context:   "Activating a Kritzkrieg or Quick-Fix ÜberCharge",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "How embarrassing. Zey let a man of science escape with ze papers!",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/65/Medic_autocappedintelligence01.wav",
		Type: 	   "Objective-related",
		SubType:   "",
		Context:   "After capturing Intelligence",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Papers, please.",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/64/Medic_autocappedintelligence02.wav",
		Type: 	   "Objective-related",
		SubType:   "",
		Context:   "After capturing Intelligence",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Vere are your precious papers now, Dummkopfs?",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/db/Medic_autocappedintelligence03.wav",
		Type: 	   "Objective-related",
		SubType:   "",
		Context:   "After capturing Intelligence",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Anuhza successful procedure!",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/d7/Medic_autocappedcontrolpoint01.wav",
		Type: 	   "Objective-related",
		SubType:   "",
		Context:   "After capturing control point",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zey are veakened!",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/89/Medic_autocappedcontrolpoint02.wav",
		Type: 	   "Objective-related",
		SubType:   "",
		Context:   "After capturing control point",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I am prepared to do vatever it takes!",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/9b/Medic_autocappedcontrolpoint03.wav",
		Type: 	   "Objective-related",
		SubType:   "",
		Context:   "After capturing control point",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Get on ze point, Dummkopf!",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/71/Medic_standonthepoint01.wav",
		Type: 	   "Objective-related",
		SubType:   "",
		Context:   "Standing on captured point, firing weapon",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Stand on ze point, Schweinhund!",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/01/Medic_standonthepoint02.wav",
		Type: 	   "Objective-related",
		SubType:   "",
		Context:   "Standing on captured point, firing weapon",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Idiot, get on ze point!",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/c7/Medic_standonthepoint03.wav",
		Type: 	   "Objective-related",
		SubType:   "",
		Context:   "Standing on captured point, firing weapon",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Idiot, stand on ze point!",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/ed/Medic_standonthepoint04.wav",
		Type: 	   "Objective-related",
		SubType:   "",
		Context:   "Standing on captured point, firing weapon",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Standing near ze point does nussing. Get on ze point, dummkopf!",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/72/Medic_standonthepoint05.wav",
		Type: 	   "Objective-related",
		SubType:   "",
		Context:   "Standing on captured point, firing weapon",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Schweinhunds.",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/8f/Medic_autodejectedtie04.wav",
		Type: 	   "Objective-related",
		SubType:   "",
		Context:   "Defense",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ha!",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/a6/Medic_positivevocalization03.wav",
		Type: 	   "Objective-related",
		SubType:   "",
		Context:   "Defense",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I am ze Übermensch! (Translation: I am the Overlord/Superman!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/4a/Medic_cheers05.wav",
		Type: 	   "Objective-related",
		SubType:   "",
		Context:   "Defense",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Oktoberfest!",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/49/Medic_cheers06.wav",
		Type: 	   "Objective-related",
		SubType:   "",
		Context:   "Defense",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Vell done!",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/e7/Medic_cheers02.wav",
		Type: 	   "Objective-related",
		SubType:   "",
		Context:   "Defense",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "It looks like Dummkopffest! (Translation: Idiot-fest!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/cc/Medic_taunts08.wav",
		Type: 	   "Objective-related",
		SubType:   "",
		Context:   "Defense",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Push!",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/f9/Medic_cartgoingforwardoffense01.wav",
		Type: 	   "Objective-related",
		SubType:   "Payload-related",
		Context:   "Attacking: Cart Goes Forward",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Puuuush!",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/ce/Medic_cartgoingforwardoffense02.wav",
		Type: 	   "Objective-related",
		SubType:   "Payload-related",
		Context:   "Attacking: Cart Goes Forward",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Everyone! Push!",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/f9/Medic_cartgoingforwardoffense03.wav",
		Type: 	   "Objective-related",
		SubType:   "Payload-related",
		Context:   "Attacking: Cart Goes Forward",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Push ze cart!",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/97/Medic_cartgoingforwardoffense04.wav",
		Type: 	   "Objective-related",
		SubType:   "Payload-related",
		Context:   "Attacking: Cart Goes Forward",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Everyone, push ze cart!",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/e9/Medic_cartgoingforwardoffense05.wav",
		Type: 	   "Objective-related",
		SubType:   "Payload-related",
		Context:   "Attacking: Cart Goes Forward",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Raus, Raus! (Translation: Go, Go!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/3/3a/Medic_cartgoingforwardoffense06.wav",
		Type: 	   "Objective-related",
		SubType:   "Payload-related",
		Context:   "Attacking: Cart Goes Forward",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Push! Schnell! (Translation: Push! Hurry!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b5/Medic_cartgoingforwardoffense07.wav",
		Type: 	   "Objective-related",
		SubType:   "Payload-related",
		Context:   "Attacking: Cart Goes Forward",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Push damn you push!",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/0d/Medic_cartgoingforwardoffense08.wav",
		Type: 	   "Objective-related",
		SubType:   "Payload-related",
		Context:   "Attacking: Cart Goes Forward",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Forvard, push ze cart forvard!",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/e6/Medic_cartgoingbackoffense01.wav",
		Type: 	   "Objective-related",
		SubType:   "Payload-related",
		Context:   "Attacking: Cart Goes Back",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Vhy is ze cart moving backvards?",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/fa/Medic_cartgoingbackoffense02.wav",
		Type: 	   "Objective-related",
		SubType:   "Payload-related",
		Context:   "Attacking: Cart Goes Back",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zhat cart must be shtopped!",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/63/Medic_cartgoingforwarddefense01.wav",
		Type: 	   "Objective-related",
		SubType:   "Payload-related",
		Context:   "Defending: Cart Goes Forward",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Shtopp zhat cart!",
		AudioFile: "https://wiki.teamfortress.com/w/images/2/22/Medic_cartgoingforwarddefense02.wav",
		Type: 	   "Objective-related",
		SubType:   "Payload-related",
		Context:   "Defending: Cart Goes Forward",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Everyone, stay close to zhe cart!",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/ec/Medic_cartstaycloseoffense01.wav",
		Type: 	   "Objective-related",
		SubType:   "Payload-related",
		Context:   "Attacking: Stay Close to Cart",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Do not leave zhe cart dummkopfs!",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/e0/Medic_cartstaycloseoffense02.wav",
		Type: 	   "Objective-related",
		SubType:   "Payload-related",
		Context:   "Attacking: Stay Close to Cart",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Stay close to zhe cart!",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/9c/Medic_cartstaycloseoffense03.wav",
		Type: 	   "Objective-related",
		SubType:   "Payload-related",
		Context:   "Attacking: Stay Close to Cart",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zhe cart is not moving!",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/63/Medic_cartstoppedoffense01.wav",
		Type: 	   "Objective-related",
		SubType:   "Payload-related",
		Context:   "Attacking: Cart Has Stopped",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Who stopped pushing zhe cart?! I want names!",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/9c/Medic_cartstoppedoffense02.wav",
		Type: 	   "Objective-related",
		SubType:   "Payload-related",
		Context:   "Attacking: Cart Has Stopped",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Vhy is no one else pushing zhis cart?!",
		AudioFile: "https://wiki.teamfortress.com/w/images/2/2a/Medic_cartstoppedoffense03.wav",
		Type: 	   "Objective-related",
		SubType:   "Payload-related",
		Context:   "Attacking: Cart Has Stopped",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Who stopped pushing zhe cart?!",
		AudioFile: "https://wiki.teamfortress.com/w/images/2/20/Medic_cartstoppedoffense04.wav",
		Type: 	   "Objective-related",
		SubType:   "Payload-related",
		Context:   "Attacking: Cart Has Stopped",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Everyone, we must stop zhat bomb!",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/54/Medic_cartstopitdefense01.wav",
		Type: 	   "Objective-related",
		SubType:   "Payload-related",
		Context:   "Defending: Stop The Bomb",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Very nice!",
		AudioFile: "https://wiki.teamfortress.com/w/images/3/32/Medic_quest_complete_easy_01.mp3",
		Type: 	   "Contract-related",
		SubType:   "",
		Context:   "Contract complete",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zat vas fun! Ha ha!",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/6b/Medic_quest_complete_easy_02.mp3",
		Type: 	   "Contract-related",
		SubType:   "",
		Context:   "Contract complete",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Vell done!",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/f6/Medic_quest_complete_easy_03.mp3",
		Type: 	   "Contract-related",
		SubType:   "",
		Context:   "Contract complete",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "(mischievous laughter)",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/02/Medic_quest_complete_easy_04.mp3",
		Type: 	   "Contract-related",
		SubType:   "",
		Context:   "Contract complete",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "(malevolent laughter)",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/62/Medic_quest_complete_easy_05.mp3",
		Type: 	   "Contract-related",
		SubType:   "",
		Context:   "Contract complete",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Oh heavens, yes!",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/5c/Medic_quest_complete_hard_01.mp3",
		Type: 	   "Contract-related",
		SubType:   "",
		Context:   "Contract complete",
		Condition: `Difficult Contract`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Perfect!",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/f4/Medic_quest_complete_hard_02.mp3",
		Type: 	   "Contract-related",
		SubType:   "",
		Context:   "Contract complete",
		Condition: `Difficult Contract`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Yes!",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/98/Medic_quest_complete_hard_05.mp3",
		Type: 	   "Contract-related",
		SubType:   "",
		Context:   "Contract complete",
		Condition: `Difficult Contract`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Hoo, hoo! Astounding!",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/47/Medic_quest_complete_hard_06.mp3",
		Type: 	   "Contract-related",
		SubType:   "",
		Context:   "Contract complete",
		Condition: `Difficult Contract`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ready!",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/02/Medic_mvm_say_ready01.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "Setup/Between Waves",
		Context:   "Ready to play",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I cannot vait, hah!",
		AudioFile: "https://wiki.teamfortress.com/w/images/3/31/Medic_mvm_say_ready02.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "Setup/Between Waves",
		Context:   "Ready to play",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Who is not ready?",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/0e/Medic_mvm_ask_ready01.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "Setup/Between Waves",
		Context:   "Ready to play",
		Condition: `Other players are not ready`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I should upgrade.",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/72/Medic_mvm_encourage_upgrade01.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "Setup/Between Waves",
		Context:   "Wave finished, near an Upgrade Station",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Get to an Upgrade Station, schnell!",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/71/Medic_mvm_encourage_upgrade02.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "Setup/Between Waves",
		Context:   "Wave finished, near an Upgrade Station",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Upgrade! Uppengraden everyvun! (Uppengraden is not a real German word. In a real German word, it would be Aufrüsten.)",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/69/Medic_mvm_encourage_upgrade03.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "Setup/Between Waves",
		Context:   "Wave finished, near an Upgrade Station",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ooh, much better.",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/6e/Medic_mvm_get_upgrade01.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "Setup/Between Waves",
		Context:   "After accessing an Upgrade Station",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I feel like a million Deutschmarks! (Standard German would be Deutsche Mark.)",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/13/Medic_mvm_get_upgrade02.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "Setup/Between Waves",
		Context:   "After accessing an Upgrade Station",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "(Laughs) I am a god.",
		AudioFile: "https://wiki.teamfortress.com/w/images/2/22/Medic_mvm_get_upgrade03.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "Setup/Between Waves",
		Context:   "After accessing an Upgrade Station",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Oh, I am going to murder so many robots.",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/56/Medic_mvm_get_upgrade04.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "Setup/Between Waves",
		Context:   "After accessing an Upgrade Station",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Come on! Collect zhe money!",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/81/Medic_mvm_collect_credits01.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Collecting Credits",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Free money! Free money!",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/63/Medic_mvm_collect_credits02.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Collecting Credits",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Everyvun! Freee money!",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/a0/Medic_mvm_collect_credits03.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Collecting Credits",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ooh, money!",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/87/Medic_mvm_collect_credits04.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Collecting Credits",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Everyone! Behind me!",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/c9/Medic_mvm_heal_shield01.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Deploying a Heal Shield",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "You vill go no furzher!",
		AudioFile: "https://wiki.teamfortress.com/w/images/2/26/Medic_mvm_heal_shield02.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Deploying a Heal Shield",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "No robot shall pass!",
		AudioFile: "https://wiki.teamfortress.com/w/images/2/2b/Medic_mvm_heal_shield03.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Deploying a Heal Shield",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Get behind me!",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/ac/Medic_mvm_heal_shield04.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Deploying a Heal Shield",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "(laughter) Zhis wall is robot death!",
		AudioFile: "https://wiki.teamfortress.com/w/images/3/37/Medic_mvm_heal_shield05.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Deploying a Heal Shield",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Sapping a robot.",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/07/Medic_mvm_robot_sapped01.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Teammate places a Sapper on a Robot",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zhe robot is sapped.",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/82/Medic_mvm_robot_sapped02.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Teammate places a Sapper on a Robot",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Sniper!",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/52/Medic_mvm_sniper01.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Enemy Sniper",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Sentry Buster!",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/83/Medic_mvm_sentry_buster01.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Sentry Buster",
		Condition: `Incoming`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Sentry Buster is destroyed!",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b0/Medic_mvm_sentry_buster02.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Sentry Buster",
		Condition: `Destroyed`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zhe bomb is clear.",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/4f/Medic_mvm_bomb_destroyed01.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Bomb dropped",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zhe bomb carrier is down.",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/ff/Medic_mvm_bomb_destroyed02.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Bomb dropped",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Bomb!",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/9d/Medic_mvm_bomb_see01.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Bomb picked up",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zhey have a bomb!",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/f3/Medic_mvm_bomb_see02.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Bomb picked up",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Another bomb!",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b2/Medic_mvm_bomb_see03.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Bomb picked up",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zhe bomb carrier is looking angry!",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/e1/Medic_mvm_bomb_upgrade01.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Bomb carrier upgrades",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zhe bomb carrier is getting angrier!",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/9b/Medic_mvm_bomb_upgrade02.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Bomb carrier upgrades",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zhe bomb carrier is furious!",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/66/Medic_mvm_bomb_upgrade03.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Bomb carrier upgrades",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Überbot!",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/e9/Medic_mvm_giant_robot01.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Giant Robot",
		Condition: `Deployed`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zhe Überbot has a bomb!",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/79/Medic_mvm_giant_robot03.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Giant Robot",
		Condition: `Picks up bomb`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zhe Überbot is destroyed.",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/16/Medic_mvm_giant_robot02.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Giant Robot",
		Condition: `Destroyed`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Taaank!",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b3/Medic_mvm_tank_alert01.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Tank",
		Condition: `Incoming`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zhe Tank is dropping a bomb!",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/bf/Medic_mvm_tank_deploy01.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Tank",
		Condition: `In Alert Zone`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Shoot zhe Tank!",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/76/Medic_mvm_tank_shooting01.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Tank",
		Condition: `Attacking`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Kill zhat Tank!",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/5a/Medic_mvm_tank_shooting02.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Tank",
		Condition: `Attacking`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Shoot at ein Kraftmaschine! (Translation: Shoot at the engine-generator! (Literally:power-machine, correct would be eine)))",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/7f/Medic_mvm_tank_shooting03.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Tank",
		Condition: `Attacking`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Scout is dead!",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/ec/Medic_mvm_class_is_dead01.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Teammate is killed",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Soldier is dead!",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/f2/Medic_mvm_class_is_dead04.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Teammate is killed",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Pyro is dead!",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/c8/Medic_mvm_class_is_dead07.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Teammate is killed",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Demo is dead!",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b8/Medic_mvm_class_is_dead06.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Teammate is killed",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Heavy is dead!",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/88/Medic_mvm_class_is_dead03.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Teammate is killed",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Engie is dead!",
		AudioFile: "https://wiki.teamfortress.com/w/images/2/23/Medic_mvm_class_is_dead09.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Teammate is killed",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Medic is dead!",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/ac/Medic_mvm_class_is_dead05.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Teammate is killed",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Sniper is dead!",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b2/Medic_mvm_class_is_dead08.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Teammate is killed",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Spy is dead!",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/04/Medic_mvm_class_is_dead02.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Teammate is killed",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "(Laughs) It's just you and me, robots!",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/a1/Medic_mvm_stand_alone01.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "All other teammates are dead",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I'm alive! Alive!",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b8/Medic_mvm_resurrect01.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Upon Being Revived With A Reanimator",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Back from zhe dead!",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/40/Medic_mvm_resurrect02.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Upon Being Revived With A Reanimator",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I'm back!",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/14/Medic_mvm_resurrect03.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Upon Being Revived With A Reanimator",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Oh, I vill tear you apart, bolt by bolt!",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/82/Medic_mvm_taunt01.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "Miscellaneous",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zhey're attacking zhe gate!",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/80/Medic_mvm_mannhattan_gate_atk01.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "",
		Condition: `Robots attacking`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zhe robots are attacking zhe gate!",
		AudioFile: "https://wiki.teamfortress.com/w/images/2/27/Medic_mvm_mannhattan_gate_atk02.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "",
		Condition: `Robots attacking`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zhe robots have taken zhe gate!",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b6/Medic_mvm_mannhattan_gate_take01.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "",
		Condition: `Robots take gate`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zhe robots have zhe gate!",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/54/Medic_mvm_mannhattan_gate_take02.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "During a Wave",
		Context:   "",
		Condition: `Robots take gate`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ve have done it!",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/10/Medic_mvm_wave_end01.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "After a Wave",
		Context:   "Won",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Robots, haha!",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/e6/Medic_mvm_wave_end02.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "After a Wave",
		Context:   "Won",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Hysterical laughter Death to robots!",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/81/Medic_mvm_wave_end03.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "After a Wave",
		Context:   "Won",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Oh, zhis is not gut.",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b5/Medic_mvm_wave_end04.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "After a Wave",
		Context:   "Lost",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ach, ve deserve to lose.",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/73/Medic_mvm_wave_end05.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "After a Wave",
		Context:   "Lost",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zhe flesh is veak.",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/c1/Medic_mvm_wave_end06.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "After a Wave",
		Context:   "Lost",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Robots are our masters.",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b7/Medic_mvm_wave_end07.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "After a Wave",
		Context:   "Lost",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ooh, zhis vill do nicely.",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/d4/Medic_mvm_loot_common01.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "After a Wave",
		Context:   "Receiving a Killstreak Kit ",
		Condition: `Common Loot`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ooh, vunderbar! (Translation: Wonderful!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/66/Medic_mvm_loot_common02.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "After a Wave",
		Context:   "Receiving a Killstreak Kit ",
		Condition: `Common Loot`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Hm, not bad.",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b0/Medic_mvm_loot_common03.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "After a Wave",
		Context:   "Receiving a Killstreak Kit ",
		Condition: `Common Loot`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Oh, now zhis is a rare piece!",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/f1/Medic_mvm_loot_rare01.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "After a Wave",
		Context:   "Receiving a Killstreak Kit ",
		Condition: `Rare Loot`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ooh, very nice.",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/eb/Medic_mvm_loot_rare02.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "After a Wave",
		Context:   "Receiving a Killstreak Kit ",
		Condition: `Rare Loot`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Vunderbar. (Translation: Wonderful.)",
		AudioFile: "https://wiki.teamfortress.com/w/images/3/30/Medic_mvm_loot_godlike01.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "After a Wave",
		Context:   "Receiving a Killstreak Kit ",
		Condition: `Godlike Loot`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "(Gasp) It's beautiful.",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/5c/Medic_mvm_loot_godlike02.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "After a Wave",
		Context:   "Receiving a Killstreak Kit ",
		Condition: `Godlike Loot`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Gott in Himmel, it's vunderful. It's more zhan vunderful, it's- it's perfect! (gleeful laughter) (Translation: God in Heaven, and correct would be im Himmel)",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/70/Medic_mvm_loot_godlike03.wav",
		Type: 	   "Mann vs. Machine",
		SubType:   "After a Wave",
		Context:   "Receiving a Killstreak Kit ",
		Condition: `Godlike Loot`,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ooh. Big head.",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/79/Medic_sf12_badmagic01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Wheel of Fate outcomes",
		Context:   "Big Head fate",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Fascinating.",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/e3/Medic_sf12_badmagic02.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Wheel of Fate outcomes",
		Context:   "Big Head fate",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ooh! Tiny little head!",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/6b/Medic_sf12_badmagic03.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Wheel of Fate outcomes",
		Context:   "Small Head fate",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Haha! Ooh! I have no head!",
		AudioFile: "https://wiki.teamfortress.com/w/images/2/20/Medic_sf12_badmagic04.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Wheel of Fate outcomes",
		Context:   "Small Head fate",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "My-my blood is entirely out of my body. Vhat a curious feeling!",
		AudioFile: "https://wiki.teamfortress.com/w/images/3/3f/Medic_sf12_badmagic11.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Wheel of Fate outcomes",
		Context:   "Whammy fate (Bleeding variant)",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ooh. Interesting.",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/f1/Medic_sf12_badmagic05.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Wheel of Fate outcomes",
		Context:   "Positive fate",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ooh. Zhis is exciting!",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b9/Medic_sf12_badmagic06.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Wheel of Fate outcomes",
		Context:   "Positive fate",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Oh ho hoh! I have been in zhe wrong profession. I must learn zhis magic!",
		AudioFile: "https://wiki.teamfortress.com/w/images/3/33/Medic_sf12_badmagic07.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Wheel of Fate outcomes",
		Context:   "Positive fate",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ooh. Vhat is happening now?",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/4b/Medic_sf12_badmagic08.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Wheel of Fate outcomes",
		Context:   "Positive fate",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Vhat a strange sensation!",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/6c/Medic_sf12_badmagic09.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Wheel of Fate outcomes",
		Context:   "Positive fate",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Wuh ho ho! Vhat a curious sensation!",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/04/Medic_sf12_badmagic12.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Wheel of Fate outcomes",
		Context:   "Positive fate",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Uhh. Uh-oh. Alright, zhis is actually really bad.",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/9f/Medic_sf12_badmagic10.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Wheel of Fate outcomes",
		Context:   "Negative fate",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Everybody! Attack ze vizard!",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/60/Medic_sf12_attack01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Merasmus appears",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Now! NOW! Attack ze vizard!",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/74/Medic_sf12_attack02.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Merasmus appears",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I vill heal you! Attack ze vizard!",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/da/Medic_sf12_attack03.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Merasmus appears",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Hoh! Zhat book certainly seems angry!",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b9/Medic_sf12_bombinomicon01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Merasmus brings out Bombinomicon",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Uh hello! Magic book? Do you still have Demoman's eye? I'll trade you a heart for it!",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b1/Medic_sf12_bombinomicon02.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Merasmus brings out Bombinomicon",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Hoh! Zhat book is full of bombs!",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/51/Medic_sf12_bombinomicon03.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Merasmus brings out Bombinomicon",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "So many bombs!",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/d6/Medic_sf12_bombinomicon04.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Merasmus brings out Bombinomicon",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Woo! What is zhat book doing?",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/6b/Medic_sf12_bombinomicon05.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Merasmus brings out Bombinomicon",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "The vizard is charging!",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/a1/Medic_sf12_charging01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Merasmus brings out Bombinomicon",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I have so much power!",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/0b/Medic_sf12_goodmagic01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Successfully stun Merasmus",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I am full of magic!",
		AudioFile: "https://wiki.teamfortress.com/w/images/3/34/Medic_sf12_goodmagic02.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Successfully stun Merasmus",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I am coming for you, vizard!",
		AudioFile: "https://wiki.teamfortress.com/w/images/3/31/Medic_sf12_goodmagic03.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Successfully stun Merasmus",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ooh. I must learn how to do zhat.",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/f7/Medic_sf12_goodmagic04.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Successfully stun Merasmus",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "He's healing himself!",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/96/Medic_sf12_healing01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Merasmus attempts to heal himself",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "KILL HIM! He's healing himself!",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/71/Medic_sf12_healing02.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Merasmus attempts to heal himself",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Vizard! Where are you?",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/e9/Medic_sf12_seeking01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Looking for Merasmus",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Vizard! Zhe sooner you come out, the sooner ve can kill you!",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/71/Medic_sf12_seeking02.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Looking for Merasmus",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Come out, Merasmus! Ve have much to discuss!",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/0c/Medic_sf12_seeking03.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Looking for Merasmus",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Come out, Merasmus! Nothing vill happen to you. I svear! (breathless laughter) I can't...ve're going to kill you! (more laughter)",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/76/Medic_sf12_seeking04.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Looking for Merasmus",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zhat vizard is hiding somevhere.",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/e5/Medic_sf12_seeking05.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Looking for Merasmus",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Merasmus?",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/d2/Medic_sf12_seeking06.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Looking for Merasmus",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Vhere are you, vizard?",
		AudioFile: "https://wiki.teamfortress.com/w/images/2/21/Medic_sf12_seeking07.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Looking for Merasmus",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Vizard!",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/fe/Medic_sf12_seeking08.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Looking for Merasmus",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "(evil laughter)",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/82/Medic_sf12_taunts02.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Looking for Merasmus",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "(happy laughter)",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/fe/Medic_sf12_taunts03.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Looking for Merasmus",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Oh. Magic. Ghosts! Oho! Zhis is so much fun!",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/5c/Medic_sf12_taunts04.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Looking for Merasmus",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Oh hohoho. I love Halloveen!",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/69/Medic_sf12_taunts05.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "During battle with Merasmus",
		Context:   "Looking for Merasmus",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "(long scream)",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/d9/Medic_sf12_falling01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Miscellaneous",
		Context:   "Falling in Bottomless Pit in Ghost Fort or Helltower (Also the same scream when falling from the cliff in Snowplow)",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "RUN!",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/53/Medic_sf12_scared01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Miscellaneous",
		Context:   "Scared",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "GET AVAY!",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/89/Medic_sf12_scared02.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Miscellaneous",
		Context:   "Scared",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "GET AVAY FROM ZHE VIZARD!",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/48/Medic_sf12_scared03.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Miscellaneous",
		Context:   "Scared",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Raus, raus! Move ze wheelchair!",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/83/Medic_sf13_cart_forward01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Pushing the Cart",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Push zat old man to hell!",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/4f/Medic_sf13_cart_forward02.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Pushing the Cart",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Push ze dead man!",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/4c/Medic_sf13_cart_forward03.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Pushing the Cart",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ze bridge is down!",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/12/Medic_sf13_midnight01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "The Witching Hour: Bridge Appears",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Everyone, get to ze bridge!!",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/cf/Medic_sf13_midnight02.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "The Witching Hour: Bridge Appears",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ze bridge!",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/55/Medic_sf13_midnight03.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "The Witching Hour: Bridge Appears",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ze clock has struck! Schnell, schnell!",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/1d/Medic_sf13_midnight06.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "The Witching Hour: Bridge Appears",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ze clock has struck!",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/e6/Medic_sf13_midnight07.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "The Witching Hour: Bridge Appears",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ooh, tingly.",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/1d/Medic_sf13_influx_small02.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Collected Normal Spell",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Today!! I am a God!! (maniacal laughter)",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/f8/Medic_sf13_influx_big02.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Collected Rare Spell",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "(maniacal laughter)",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/11/Medic_sf13_influx_big03.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Collected Rare Spell",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Vhat is happening?!",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/10/Medic_sf13_magic_reac01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Reacting to a Spell",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zhe horror! Zhe horror!",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/fd/Medic_sf13_magic_reac02.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Reacting to a Spell",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I can't take any more of zis insanity!",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/89/Medic_sf13_magic_reac03.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Reacting to a Spell",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ahh! Insanity!",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/aa/Medic_sf13_magic_reac04.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Reacting to a Spell",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Someone make zhe magic stop!",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/52/Medic_sf13_magic_reac05.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Reacting to a Spell",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Too much magic!",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/75/Medic_sf13_magic_reac06.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Reacting to a Spell",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I can't take it any more!",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/a6/Medic_sf13_magic_reac07.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Reacting to a Spell",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Caputus crepitus!",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/ba/Medic_sf13_spell_bombhead01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Pactum diabolus!",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/52/Medic_sf13_spell_devil_bargain01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Seismela tremoro!",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/fa/Medic_sf13_spell_earthquake01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Barpo kabalto!",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b8/Medic_sf13_spell_generic04.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Barpo invisium!",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/54/Medic_sf13_spell_invisibility01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Imputum fulmenus!",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/c9/Medic_sf13_spell_lightning_bolt01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Invokum Monoculus!",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/e8/Medic_sf13_spell_summon_monoculous01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Amplus tripudio!",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/7b/Medic_sf13_spell_super_jump01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Paidum celeris!",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/8d/Medic_sf13_spell_super_speed01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ipsum instantarium!",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/c7/Medic_sf13_spell_teleport_self01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Deus invictus!",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/e4/Medic_sf13_spell_uber01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Mortis animataris!",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/67/Medic_sf13_spell_zombie_horde01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I'm going to saw through your bones!",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/8d/Medic_taunts05.wav",
		Type: 	   "Dueling",
		SubType:   "",
		Context:   "Starting a Duel",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I am prepared to do vatever it takes!",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/9b/Medic_autocappedcontrolpoint03.wav",
		Type: 	   "Dueling",
		SubType:   "",
		Context:   "Starting a Duel",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Prepare for your examination... (laughs)",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/45/Medic_taunts10.wav",
		Type: 	   "Dueling",
		SubType:   "",
		Context:   "Starting a Duel",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "You are trying my patience!",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/e5/Medic_jeers06.wav",
		Type: 	   "Dueling",
		SubType:   "",
		Context:   "Starting a Duel",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Hyaaaa!",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/c2/Medic_battlecry04.wav",
		Type: 	   "Dueling",
		SubType:   "",
		Context:   "Duel Accepted",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Wunderbar! (Translation: Wonderful!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/63/Medic_positivevocalization02.wav",
		Type: 	   "Dueling",
		SubType:   "",
		Context:   "Duel Accepted",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ja. (Translation: Yes.)",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/fb/Medic_yes01.wav",
		Type: 	   "Dueling",
		SubType:   "",
		Context:   "Duel Accepted",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Jawohl. (Translation: Yes!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/cc/Medic_yes02.wav",
		Type: 	   "Dueling",
		SubType:   "",
		Context:   "Duel Accepted",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zis... is unacceptable!",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/49/Medic_autodejectedtie01.wav",
		Type: 	   "Dueling",
		SubType:   "",
		Context:   "Duel Rejected",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "You are... schtupid!",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/5f/Medic_taunts11.wav",
		Type: 	   "Dueling",
		SubType:   "",
		Context:   "Duel Rejected",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Hawww!",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b5/Medic_autodejectedtie07.wav",
		Type: 	   "Dueling",
		SubType:   "",
		Context:   "Duel Rejected",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Booo!",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/56/Medic_jeers05.wav",
		Type: 	   "Dueling",
		SubType:   "",
		Context:   "Duel Rejected",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Schweinhunds!",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/fc/Medic_jeers12.wav",
		Type: 	   "Dueling",
		SubType:   "",
		Context:   "Duel Rejected",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I am Archimedes!",
		AudioFile: "https://wiki.teamfortress.com/w/images/2/21/Medic_item_birdhead_round_start01.wav",
		Type: 	   "Item-related",
		SubType:   "With Medimedes equipped",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I experimented on my own head! (laughs maniacally)",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/d1/Medic_item_birdhead_round_start02.wav",
		Type: 	   "Item-related",
		SubType:   "With Medimedes equipped",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "My head! (laughs)",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/7f/Medic_item_birdhead_round_start03.wav",
		Type: 	   "Item-related",
		SubType:   "With Medimedes equipped",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Zhe bird head is pure agony! (laughs manically)",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/a2/Medic_item_birdhead_round_start04.wav",
		Type: 	   "Item-related",
		SubType:   "With Medimedes equipped",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "It's a bird! It's a head! It's a bird head! (laughs)",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/e7/Medic_item_birdhead_round_start05.wav",
		Type: 	   "Item-related",
		SubType:   "With Medimedes equipped",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Help me! (Unstable laughter)",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/9a/Medic_item_birdhead_round_start06.wav",
		Type: 	   "Item-related",
		SubType:   "With Medimedes equipped",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Bird head was a bad choice! (screams)",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/60/Medic_item_birdhead_round_start07.wav",
		Type: 	   "Item-related",
		SubType:   "With Medimedes equipped",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I toiled in God's domain! (screams)",
		AudioFile: "https://wiki.teamfortress.com/w/images/2/24/Medic_item_birdhead_round_start08.wav",
		Type: 	   "Item-related",
		SubType:   "With Medimedes equipped",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Bird head domination!",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/0f/Medic_item_birdhead_domination01.wav",
		Type: 	   "Item-related",
		SubType:   "With Medimedes equipped",
		Context:   "Domination",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I have a bird head, you're dominated! *sotto voce* Ve're bozh having a bad day.",
		AudioFile: "https://wiki.teamfortress.com/w/images/2/2e/Medic_item_birdhead_domination02.wav",
		Type: 	   "Item-related",
		SubType:   "With Medimedes equipped",
		Context:   "Domination",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I am zhe angry bird god of zhe Badlands! Fear me!",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/bf/Medic_item_birdhead_uber01.wav",
		Type: 	   "Item-related",
		SubType:   "With Medimedes equipped",
		Context:   "Ubercharge",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Let's do zhis, my friends! Evilly: Kill zhem all. Normally: Shh, it's enough!",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/e2/Medic_item_secop_round_start01.wav",
		Type: 	   "Item-related",
		SubType:   "With Second Opinion equipped",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I'm ready, my friends. Evilly: Kill all your friends. Normally: Ooh, good idea.",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/ef/Medic_item_secop_round_start02.wav",
		Type: 	   "Item-related",
		SubType:   "With Second Opinion equipped",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I'm ready! Evilly: Kill zhem all. Normally: Also I must kill you all.",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/06/Medic_item_secop_round_start03.wav",
		Type: 	   "Item-related",
		SubType:   "With Second Opinion equipped",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I cannot vait (nervous giggle) Evilly: And neizher can I.",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/90/Medic_item_secop_round_start04.wav",
		Type: 	   "Item-related",
		SubType:   "With Second Opinion equipped",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Evilly: Kill zhem, kill zhem all. Normally: Hm, zhat does sound like fun.",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b2/Medic_item_secop_round_start05.wav",
		Type: 	   "Item-related",
		SubType:   "With Second Opinion equipped",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Evilly: Kill zhem all. Normally: Hm. Are you sure? Evilly: Yes. Normally:Vell, I'm convinced.",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/4a/Medic_item_secop_round_start06.wav",
		Type: 	   "Item-related",
		SubType:   "With Second Opinion equipped",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Evilly: Zhey all zhink you're crazy. Normally: Vhat? I'll show zhem!",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/d5/Medic_item_secop_round_start07.wav",
		Type: 	   "Item-related",
		SubType:   "With Second Opinion equipped",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ready? Evilly: Ve're both ready.",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/da/Medic_item_secop_round_start08.wav",
		Type: 	   "Item-related",
		SubType:   "With Second Opinion equipped",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Who stopped pushing zhe cart? Evilly: Zhis is your fault!",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/a2/Medic_item_secop_cart_stopped01.wav",
		Type: 	   "Item-related",
		SubType:   "With Second Opinion equipped",
		Context:   "Cart Has Stopped/Pushing Cart",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Evilly: Push harder! Normally: Oh, shut up!",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/02/Medic_item_secop_cart_push03.wav",
		Type: 	   "Item-related",
		SubType:   "With Second Opinion equipped",
		Context:   "Cart Has Stopped/Pushing Cart",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Evilly: Keep pushing. Normally: Vhy don't you push?",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/6d/Medic_item_secop_cart_push04.wav",
		Type: 	   "Item-related",
		SubType:   "With Second Opinion equipped",
		Context:   "Cart Has Stopped/Pushing Cart",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "I'm of two minds about zhis. Both are--pretty good with it.",
		AudioFile: "https://wiki.teamfortress.com/w/images/2/2e/Medic_item_secop_domination01.wav",
		Type: 	   "Item-related",
		SubType:   "With Second Opinion equipped",
		Context:   "Domination",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Evilly: Do you ever worry you might be going mad!? Normally: Well, not worry. I mean, I'm not up at night about it.",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/d3/Medic_item_secop_idle01.wav",
		Type: 	   "Item-related",
		SubType:   "With Second Opinion equipped",
		Context:   "Idle",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Evilly: Do you ever zhink zhat you might be going mad? Normally: Oh, all zhe time. I don't zhink it's anyzhing to worry about.",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/c9/Medic_item_secop_idle02.wav",
		Type: 	   "Item-related",
		SubType:   "With Second Opinion equipped",
		Context:   "Idle",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Evilly: Redrum, redrum! Normally: Red- Oh, I just got zhat. Very clever.",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/f6/Medic_item_secop_idle03.wav",
		Type: 	   "Item-related",
		SubType:   "With Second Opinion equipped",
		Context:   "Idle",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ve did it! Evilly: I did it. Normally: Eh, vhatever.",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/88/Medic_item_secop_kill_assist01.wav",
		Type: 	   "Item-related",
		SubType:   "With Second Opinion equipped",
		Context:   "Kill Assist",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Ve are invincible! Evilly: Yes, ve are.",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/09/Medic_item_secop_uber01.wav",
		Type: 	   "Item-related",
		SubType:   "With Second Opinion equipped",
		Context:   "Ubercharge",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Archimedes: Bwarrrr, dominated! Bwaaaark!",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/c5/Medic_item_zombiebird_dominated01.wav",
		Type: 	   "Item-related",
		SubType:   "With Archimedes the Undying equipped",
		Context:   "Domination",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Archimedes: Bwarrrr, stole the briefcase! Raawk! Medic: Shh shh shh!",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/96/Medic_item_zombiebird_got_briefcase01.wav",
		Type: 	   "Item-related",
		SubType:   "With Archimedes the Undying equipped",
		Context:   "After capturing Intelligence",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Archimedes: Bwark, that's jarate! Medic:(sad voice) Yes, it is.",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/d8/Medic_item_zombiebird_jarate01.wav",
		Type: 	   "Item-related",
		SubType:   "With Archimedes the Undying equipped",
		Context:   "Hit by Jarate or Mad Milk",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Archimedes: Rrrooowl, upgrade station! Raawk! Medic: Ah. Yes.",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/f6/Medic_item_zombiebird_mvm_go_upgrade01.wav",
		Type: 	   "Item-related",
		SubType:   "With Archimedes the Undying equipped",
		Context:   "Wave finished, near an Upgrade Station",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Medic: Ve did it! Haha! Archimedes: Rraaaaa, kill your friends! Medic: Ah yes, I almost forgot.",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/e9/Medic_item_zombiebird_mvm_win01.wav",
		Type: 	   "Item-related",
		SubType:   "With Archimedes the Undying equipped",
		Context:   "Won",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Archimedes: Rraaa, we're on fire! Medic: Yes, I know!",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b4/Medic_item_zombiebird_on_fire01.wav",
		Type: 	   "Item-related",
		SubType:   "With Archimedes the Undying equipped",
		Context:   "Set on Fire",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Archimedes: Bwark, kill them all! Medic: Shh.",
		AudioFile: "https://wiki.teamfortress.com/w/images/2/21/Medic_item_zombiebird_round_start01.wav",
		Type: 	   "Item-related",
		SubType:   "With Archimedes the Undying equipped",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Archimedes: Bwarr. Medic: Shh. Archimedes: Raaaarl. Medic: Shh shh shh! Archimedes: Kill them all... Medic: That's enough!",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/f3/Medic_item_zombiebird_round_start02.wav",
		Type: 	   "Item-related",
		SubType:   "With Archimedes the Undying equipped",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Archimedes: Bwaaarrrl, dead by dawn! Medic: Shh, silence!.",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/5c/Medic_item_zombiebird_round_start03.wav",
		Type: 	   "Item-related",
		SubType:   "With Archimedes the Undying equipped",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Archimedes: Bwaaarrrl, Archimedes wants brains! Medic: Thank you, Archimedes.",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/cf/Medic_item_zombiebird_round_start04.wav",
		Type: 	   "Item-related",
		SubType:   "With Archimedes the Undying equipped",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Archimedes: Bwaaarrrl, braaaains! Bwaaark! Medic: Shush, Archimedes.",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/f5/Medic_item_zombiebird_round_start05.wav",
		Type: 	   "Item-related",
		SubType:   "With Archimedes the Undying equipped",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Archimedes: Bwaaarrrl, Archimedes wants brains! Medic: Yes, Archimedes wants all the brains, doesn't he?",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/5e/Medic_item_zombiebird_round_start06.wav",
		Type: 	   "Item-related",
		SubType:   "With Archimedes the Undying equipped",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Archimedes: Bwark, push the dead man! Medic: I'm trying...",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/4c/Medic_item_zombiebird_sf13_cart_forward01.wav",
		Type: 	   "Item-related",
		SubType:   "With Archimedes the Undying equipped",
		Context:   "Pushing the Cart on Helltower",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Archimedes: Bwaaarl, send him to hell! Medic: Ah, yes.",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/e2/Medic_item_zombiebird_sf13_cart_forward02.wav",
		Type: 	   "Item-related",
		SubType:   "With Archimedes the Undying equipped",
		Context:   "Pushing the Cart on Helltower",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Archimedes: Bwaaaark, stand on the point!",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/10/Medic_item_zombiebird_stand_point01.wav",
		Type: 	   "Item-related",
		SubType:   "With Archimedes the Undying equipped",
		Context:   "Standing on captured point, firing weapon",
		Condition: ``,
	},
	
	{
		Class: 		class.MEDIC,
		Response:  "Hello, Fräuleins! (Cheery, taunting voice) (Translation: Hello, (young) Ladies!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/ac/Medic_taunts07.wav",
		Type: 	   "Unused Responses",
		SubType:   "",
		Context:   "Unknown Condition",
		Condition: ``,
	},
	
}
