// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-09-17 17:48:44.5688829 +0200 CEST m=+11.788634901
// using data from
// https://wiki.teamfortress.com/wiki/pyro_responses
package responses

var pyroResponses = []Response{
	
	{
		Class: 		PYRO,
		Response:  "Ow dow how dow. (Possibly I'm on fire now, or I don't think so or Not in my house or Oh well hi there!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/d5/Pyro_taunts04.wav",
		Type: 	   "Kill-related",
		SubType:   "",
		Context:   "After Killing More than 1 Enemy in 20 Seconds with a Primary Weapon",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Mmph mphna mprh. (Possibly Thanks for the hand, Thanks for the help..)",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/ad/Pyro_specialcompleted-assistedkill01.wav",
		Type: 	   "Kill-related",
		SubType:   "",
		Context:   "Kill assist",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Murr hurr mphuphurrur, hurr mph phrr. (Possibly I didn't really think I would kill you like that.)",
		AudioFile: "https://wiki.teamfortress.com/w/images/2/2c/Pyro_taunts01.wav",
		Type: 	   "Kill-related",
		SubType:   "",
		Context:   "Melee kill",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Murr hurr mphuphurrur, hurr mph phrr. (Possibly The little ones bite, but they're still not a threat... or I didn't really think I would kill you like that. or You didn't even fight, but that's still not a dodge. or I know you didn't fight, but it still ain't a job., said differently than above)",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/02/Pyro_taunts02.wav",
		Type: 	   "Kill-related",
		SubType:   "",
		Context:   "Melee kill",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Murr hurr mphuphurrur, hurr mph phrr. (Possibly I don't think your momma ever told you not to play with fire...)",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/95/Pyro_taunts03.wav",
		Type: 	   "Kill-related",
		SubType:   "",
		Context:   "Melee kill",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Evil laugh",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/52/Pyro_laughevil01.wav",
		Type: 	   "Domination-related",
		SubType:   "",
		Context:   "Domination",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Evil laugh 2",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/d3/Pyro_laughevil02.wav",
		Type: 	   "Domination-related",
		SubType:   "",
		Context:   "Domination",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Long laugh",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/72/Pyro_laughlong01.wav",
		Type: 	   "Domination-related",
		SubType:   "",
		Context:   "Domination",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Happy laugh",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/c0/Pyro_laughhappy01.wav",
		Type: 	   "Domination-related",
		SubType:   "",
		Context:   "Domination",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Mmmmmmmrrrrrrrpppghhh! (Possibly Come on!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/dd/Pyro_battlecry01.wav",
		Type: 	   "Domination-related",
		SubType:   "",
		Context:   "Revenge Kill",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Hudda hudda huh! (Possibly They can go to hell!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/52/Pyro_activatecharge01.wav",
		Type: 	   "Domination-related",
		SubType:   "",
		Context:   "Revenge Kill",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Hudda hudda huuh! (Possibly They can go to hell!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/3/34/Pyro_battlecry02.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Mmmmmmmrrrrrrrpppghhh! (Possibly Come on!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/dd/Pyro_battlecry01.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Mhhhhoooooo! (Jeering.)(Boo!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/11/Pyro_jeers01.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "Sudden Death",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Mrghfrr! (Possibly You guys--! or You failed! or The hell? or My God!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/e2/Pyro_jeers02.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "Sudden Death",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Mmmrpgh crpyha drghya! (Possibly Can't believe that someone would do that, or Now I need a towel.)",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/90/Pyro_autodejectedtie01.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "Stalemate",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Mmmh,mmh! (Possibly Fire! Fire!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/43/Pyro_autoonfire01.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "Set on Fire",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Mmmrgh!",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/44/Pyro_autoonfire02.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "Set on Fire",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "*Dying muffled scream*",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/fc/Pyro_paincrticialdeath01.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "On Death",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "*Dying muffled scream*",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/a4/Pyro_paincrticialdeath02.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "On Death",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "*Dying muffled scream*",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/cd/Pyro_paincrticialdeath03.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "On Death",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Mmmrpgh crpyha drghya! (Possibly Can't believe that someone would do that.)",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/90/Pyro_autodejectedtie01.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "Hit by Jarate, Mad Milk, Mutated Milk, Self-Aware Beauty Mark, or the Gas Passer",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Mmmrgh!",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/44/Pyro_autoonfire02.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "Hit by Jarate, Mad Milk, Mutated Milk, Self-Aware Beauty Mark, or the Gas Passer",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Mmphn frphha herrpha. (Possibly Thanks for the teleport. or Thanks for the teleporter.)",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/cf/Pyro_thanksfortheteleporter01.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "Teleportation",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Mhnk nhya mhph. (Possibly Thank you, doc.)",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/04/Pyro_thanksfortheheal01.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "Healed by Medic",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Mumbling gibberish (Possibly Oh really? I'm paying myself after that! or You idiots aren't the only ones I'll burn today! or even You idiots aren't the only ones I've burned today!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/c2/Pyro_specialcompleted01.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "Under the effects of an ÜberCharge",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Long laugh",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/72/Pyro_laughlong01.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "Under the effects of an ÜberCharge",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Mmmphya harrgh mrgha hrghgph! (Possibly I don't know why I've got to do everything. or I gotta do the job of everyone!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/19/Pyro_autocappedintelligence01.wav",
		Type: 	   "Objective-related",
		SubType:   "",
		Context:   "After Capturing Intelligence",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Hurrururururu!(Possibly This point is ours!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/c5/Pyro_autocappedcontrolpoint01.wav",
		Type: 	   "Objective-related",
		SubType:   "",
		Context:   "After Capturing control point",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Mrh! Hrt hr nha phrnt yrh mrprph! (Possibly Just stand on the point, you idiots or Come stand on the point, goddammit!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/67/Pyro_standonthepoint01.wav",
		Type: 	   "Objective-related",
		SubType:   "",
		Context:   "Standing on captured Point, firing weapon",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Mrfer! (Possibly Incoming!, Victory! or Let's kill-em-all!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/4a/Pyro_cheers01.wav",
		Type: 	   "Objective-related",
		SubType:   "",
		Context:   "Defense",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Heh dum dummad (Possibly We're gonna kill em all!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/67/Cm_pyro_pregamewonlast_01.mp3",
		Type: 	   "Competitive Mode",
		SubType:   "Setup",
		Context:   "Previous round was a win",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Awwwww!",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/91/Cm_pyro_pregamelostlast_01.mp3",
		Type: 	   "Competitive Mode",
		SubType:   "Setup",
		Context:   "Previous round was a loss",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Heh thubba theh then, wohha? (Possibly We're gonna let them beat us?)",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/ac/Cm_pyro_pregamelostlast_02.mp3",
		Type: 	   "Competitive Mode",
		SubType:   "Setup",
		Context:   "Previous round was a loss",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Yah fuddah gon den dey fhumah! (Possibly You sure should stop dying...Mph!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/9c/Cm_pyro_pregamelostlast_03.mp3",
		Type: 	   "Competitive Mode",
		SubType:   "Setup",
		Context:   "Previous round was a loss",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "*Small chuckle*",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/56/Pyro_sf13_influx_small01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Collected Normal Spell",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "*Evil laugh*",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/d2/Pyro_sf13_influx_big01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Collected Rare Spell",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Mumuno, muh bumuno! (Pactum diabolus! and Mortis animataris!) (Casting pumpkin bombs or skeletons spells)",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/cf/Pyro_sf13_spell_generic01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Bumunuh, bun! (Imputum fulminus!) (Casting ball of light spell)",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/fc/Pyro_sf13_spell_generic02.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Buh blumunuh! (Amplus tripudio!) (Casting superjump spell)",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/05/Pyro_sf13_spell_generic03.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Cuhts me trihp! (Deus invictus! and Barpo kabalto!) (Casting ball of bats or healing spells)",
		AudioFile: "https://wiki.teamfortress.com/w/images/3/33/Pyro_sf13_spell_generic04.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Muphituh lurr! (Barpo invisium!) (Casting invisibility spell)",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/6a/Pyro_sf13_spell_generic05.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Muhk niphurr! (Ipsum instanterium! and Seismela tremoro!) (Casting teleport or rain of fireballs spells)",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/55/Pyro_sf13_spell_generic06.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Buh phuh murrit uph truph! (Unused)",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/12/Pyro_sf13_spell_generic07.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Cuhts me trihp! (Paidum celeris!) (Casting minify spell)",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/a5/Pyro_sf13_spell_generic08.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Muhk muttuh! (Invokum Monoculus!) (Casting Monoculus invocation spell)",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/02/Pyro_sf13_spell_generic09.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Mmmphya harrgh mrgha hrghgph! (Possibly I gotta do the job of everyone. or I don't know why I've got to do everything.)",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/19/Pyro_autocappedintelligence01.wav",
		Type: 	   "Duel-related",
		SubType:   "",
		Context:   "Starting a Duel",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Eeuaghafvada... (Possibly Oh, the horror.. or Oh, my God.)",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b2/Pyro_negativevocalization01.wav",
		Type: 	   "Duel-related",
		SubType:   "",
		Context:   "Starting a Duel",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Mmmh, mmmh!",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/43/Pyro_autoonfire01.wav",
		Type: 	   "Duel-related",
		SubType:   "",
		Context:   "Duel Accepted",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Ow dow how dow.",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/d5/Pyro_taunts04.wav",
		Type: 	   "Duel-related",
		SubType:   "",
		Context:   "Duel Accepted",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Mmph mphna.",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/47/Pyro_thanks01.wav",
		Type: 	   "Duel-related",
		SubType:   "",
		Context:   "Duel Accepted",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Mmmrpgh crpyha drghya!",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/90/Pyro_autodejectedtie01.wav",
		Type: 	   "Duel-related",
		SubType:   "",
		Context:   "Duel Rejected",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Hudda hudda huh!",
		AudioFile: "https://wiki.teamfortress.com/w/images/3/34/Pyro_battlecry02.wav",
		Type: 	   "Duel-related",
		SubType:   "",
		Context:   "Duel Rejected",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Ah hyro ifva phy! (Possibly That *muffled* is a spy! or That person is a spy! or Hey there is a Spy!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/5a/Pyro_cloakedspyidentify01.wav",
		Type: 	   "Duel-related",
		SubType:   "",
		Context:   "Duel Rejected",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Helfp ee cafpter! (Possibly Help me capture! or Help me cap this!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b1/Pyro_helpmecapture01.wav",
		Type: 	   "Duel-related",
		SubType:   "",
		Context:   "Duel Rejected",
		Condition: ``,
	},
	
	{
		Class: 		PYRO,
		Response:  "Helfp ee defen! (Possibly Help me defend!)",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/1a/Pyro_helpmedefend01.wav",
		Type: 	   "Duel-related",
		SubType:   "",
		Context:   "Duel Rejected",
		Condition: ``,
	},
	
}
