// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-09-18 18:50:52.6330427 +0200 CEST m=+0.397996801
// using data from
// https://wiki.teamfortress.com/wiki/pyro_responses
package responses

import "github.com/MattIzSpooky/tf2.rest/class"

var pyroResponses = []Response{
	
	{
		Class: 		class.PYRO,
		Response:  "Ow dow how dow.",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/d5/Pyro_taunts04.wav",
		Type: 	   "Kill-related",
		SubType:   "",
		Context:   "After Killing More than 1 Enemy in 20 Seconds with a Primary Weapon",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Mmph mphna mprh.",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/ad/Pyro_specialcompleted-assistedkill01.wav",
		Type: 	   "Kill-related",
		SubType:   "",
		Context:   "Kill assist",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Murr hurr mphuphurrur, hurr mph phrr.",
		AudioFile: "https://wiki.teamfortress.com/w/images/2/2c/Pyro_taunts01.wav",
		Type: 	   "Kill-related",
		SubType:   "",
		Context:   "Melee kill",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Murr hurr mphuphurrur, hurr mph phrr.",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/02/Pyro_taunts02.wav",
		Type: 	   "Kill-related",
		SubType:   "",
		Context:   "Melee kill",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Murr hurr mphuphurrur, hurr mph phrr.",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/95/Pyro_taunts03.wav",
		Type: 	   "Kill-related",
		SubType:   "",
		Context:   "Melee kill",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Evil laugh",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/52/Pyro_laughevil01.wav",
		Type: 	   "Domination-related",
		SubType:   "",
		Context:   "Domination",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Evil laugh 2",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/d3/Pyro_laughevil02.wav",
		Type: 	   "Domination-related",
		SubType:   "",
		Context:   "Domination",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Long laugh",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/72/Pyro_laughlong01.wav",
		Type: 	   "Domination-related",
		SubType:   "",
		Context:   "Domination",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Happy laugh",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/c0/Pyro_laughhappy01.wav",
		Type: 	   "Domination-related",
		SubType:   "",
		Context:   "Domination",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Mmmmmmmrrrrrrrpppghhh!",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/dd/Pyro_battlecry01.wav",
		Type: 	   "Domination-related",
		SubType:   "",
		Context:   "Revenge Kill",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Hudda hudda huh!",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/52/Pyro_activatecharge01.wav",
		Type: 	   "Domination-related",
		SubType:   "",
		Context:   "Revenge Kill",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Hudda hudda huuh!",
		AudioFile: "https://wiki.teamfortress.com/w/images/3/34/Pyro_battlecry02.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Mmmmmmmrrrrrrrpppghhh!",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/dd/Pyro_battlecry01.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "Round Start",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Mhhhhoooooo!",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/11/Pyro_jeers01.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "Sudden Death",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Mrghfrr!",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/e2/Pyro_jeers02.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "Sudden Death",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Mmmrpgh crpyha drghya!",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/90/Pyro_autodejectedtie01.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "Stalemate",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Mmmh,mmh!",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/43/Pyro_autoonfire01.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "Set on Fire",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Mmmrgh!",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/44/Pyro_autoonfire02.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "Set on Fire",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "*Dying muffled scream*",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/fc/Pyro_paincrticialdeath01.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "On Death",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "*Dying muffled scream*",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/a4/Pyro_paincrticialdeath02.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "On Death",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "*Dying muffled scream*",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/cd/Pyro_paincrticialdeath03.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "On Death",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Mmmrpgh crpyha drghya!",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/90/Pyro_autodejectedtie01.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "Hit by Jarate, Mad Milk, Mutated Milk, Self-Aware Beauty Mark, or the Gas Passer",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Mmmrgh!",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/44/Pyro_autoonfire02.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "Hit by Jarate, Mad Milk, Mutated Milk, Self-Aware Beauty Mark, or the Gas Passer",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Mmphn frphha herrpha.",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/cf/Pyro_thanksfortheteleporter01.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "Teleportation",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Mhnk nhya mhph.",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/04/Pyro_thanksfortheheal01.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "Healed by Medic",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Mumbling gibberish",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/c2/Pyro_specialcompleted01.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "Under the effects of an ÜberCharge",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Long laugh",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/72/Pyro_laughlong01.wav",
		Type: 	   "Event-related",
		SubType:   "",
		Context:   "Under the effects of an ÜberCharge",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Mmmphya harrgh mrgha hrghgph!",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/19/Pyro_autocappedintelligence01.wav",
		Type: 	   "Objective-related",
		SubType:   "",
		Context:   "After Capturing Intelligence",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Hurrururururu!",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/c5/Pyro_autocappedcontrolpoint01.wav",
		Type: 	   "Objective-related",
		SubType:   "",
		Context:   "After Capturing control point",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Mrh! Hrt hr nha phrnt yrh mrprph!",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/67/Pyro_standonthepoint01.wav",
		Type: 	   "Objective-related",
		SubType:   "",
		Context:   "Standing on captured Point, firing weapon",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Mrfer!",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/4a/Pyro_cheers01.wav",
		Type: 	   "Objective-related",
		SubType:   "",
		Context:   "Defense",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Heh dum dummad",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/67/Cm_pyro_pregamewonlast_01.mp3",
		Type: 	   "Competitive Mode",
		SubType:   "Setup",
		Context:   "Previous round was a win",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Awwwww!",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/91/Cm_pyro_pregamelostlast_01.mp3",
		Type: 	   "Competitive Mode",
		SubType:   "Setup",
		Context:   "Previous round was a loss",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Heh thubba theh then, wohha?",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/ac/Cm_pyro_pregamelostlast_02.mp3",
		Type: 	   "Competitive Mode",
		SubType:   "Setup",
		Context:   "Previous round was a loss",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Yah fuddah gon den dey fhumah!",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/9c/Cm_pyro_pregamelostlast_03.mp3",
		Type: 	   "Competitive Mode",
		SubType:   "Setup",
		Context:   "Previous round was a loss",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "*Small chuckle*",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/56/Pyro_sf13_influx_small01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Collected Normal Spell",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "*Evil laugh*",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/d2/Pyro_sf13_influx_big01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Collected Rare Spell",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Mumuno, muh bumuno!",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/cf/Pyro_sf13_spell_generic01.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Bumunuh, bun!",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/fc/Pyro_sf13_spell_generic02.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Buh blumunuh!",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/05/Pyro_sf13_spell_generic03.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Cuhts me trihp!",
		AudioFile: "https://wiki.teamfortress.com/w/images/3/33/Pyro_sf13_spell_generic04.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Muphituh lurr!",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/6a/Pyro_sf13_spell_generic05.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Muhk niphurr!",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/55/Pyro_sf13_spell_generic06.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Buh phuh murrit uph truph!",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/12/Pyro_sf13_spell_generic07.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Cuhts me trihp!",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/a5/Pyro_sf13_spell_generic08.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Muhk muttuh!",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/02/Pyro_sf13_spell_generic09.wav",
		Type: 	   "Halloween / Full Moon",
		SubType:   "Helltower",
		Context:   "Casting Spells",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Mmmphya harrgh mrgha hrghgph!",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/19/Pyro_autocappedintelligence01.wav",
		Type: 	   "Duel-related",
		SubType:   "",
		Context:   "Starting a Duel",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Eeuaghafvada...",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b2/Pyro_negativevocalization01.wav",
		Type: 	   "Duel-related",
		SubType:   "",
		Context:   "Starting a Duel",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Mmmh, mmmh!",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/43/Pyro_autoonfire01.wav",
		Type: 	   "Duel-related",
		SubType:   "",
		Context:   "Duel Accepted",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Ow dow how dow.",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/d5/Pyro_taunts04.wav",
		Type: 	   "Duel-related",
		SubType:   "",
		Context:   "Duel Accepted",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Mmph mphna.",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/47/Pyro_thanks01.wav",
		Type: 	   "Duel-related",
		SubType:   "",
		Context:   "Duel Accepted",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Mmmrpgh crpyha drghya!",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/90/Pyro_autodejectedtie01.wav",
		Type: 	   "Duel-related",
		SubType:   "",
		Context:   "Duel Rejected",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Hudda hudda huh!",
		AudioFile: "https://wiki.teamfortress.com/w/images/3/34/Pyro_battlecry02.wav",
		Type: 	   "Duel-related",
		SubType:   "",
		Context:   "Duel Rejected",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Ah hyro ifva phy!",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/5a/Pyro_cloakedspyidentify01.wav",
		Type: 	   "Duel-related",
		SubType:   "",
		Context:   "Duel Rejected",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Helfp ee cafpter!",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b1/Pyro_helpmecapture01.wav",
		Type: 	   "Duel-related",
		SubType:   "",
		Context:   "Duel Rejected",
		Condition: ``,
	},
	
	{
		Class: 		class.PYRO,
		Response:  "Helfp ee defen!",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/1a/Pyro_helpmedefend01.wav",
		Type: 	   "Duel-related",
		SubType:   "",
		Context:   "Duel Rejected",
		Condition: ``,
	},
	
}
