// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-09-16 23:10:05.0489711 +0200 CEST m=+1.957667001
// using data from
// https://wiki.teamfortress.com/wiki/scout_responses
package responses

var scoutResponses = []Response{
	
	{
		Class: SCOUT,
		Response: "That's what I'm talking about!",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/ea/Scout_goodjob02.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with a Primary Weapon",
		Condition: "",
	},
	
	{
		Class: SCOUT,
		Response: "[Evil Laughter]",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/64/Scout_laughevil02.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with a Primary Weapon",
		Condition: "",
	},
	
	{
		Class: SCOUT,
		Response: "[Happy Laughter]",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/da/Scout_laughhappy01.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with a Primary Weapon",
		Condition: "",
	},
	
	{
		Class: SCOUT,
		Response: "[Happy Laughter 2] You got owned!",
		AudioFile: "https://wiki.teamfortress.com/w/images/3/38/Scout_laughhappy02.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with a Primary Weapon",
		Condition: "",
	},
	
	{
		Class: SCOUT,
		Response: "[Happy Laughter 3]",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/62/Scout_laughhappy03.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with a Primary Weapon",
		Condition: "",
	},
	
	{
		Class: SCOUT,
		Response: "[Happy Laughter 4]",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/85/Scout_laughhappy04.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with a Primary Weapon",
		Condition: "",
	},
	
	{
		Class: SCOUT,
		Response: "[Long Laughter] Yeah...yeah!",
		AudioFile: "https://wiki.teamfortress.com/w/images/d/d9/Scout_laughlong01.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with a Primary Weapon",
		Condition: "",
	},
	
	{
		Class: SCOUT,
		Response: "[Long Laughter 2]",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/7a/Scout_laughlong02.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with a Primary Weapon",
		Condition: "",
	},
	
	{
		Class: SCOUT,
		Response: "Not so tough now are ya? Are ya?!",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/52/Scout_taunts04.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with a Primary Weapon",
		Condition: "",
	},
	
	{
		Class: SCOUT,
		Response: "You knuckleheads ain't even worth the effort.",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/a5/Scout_taunts16.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with a Primary Weapon",
		Condition: "",
	},
	
}
