// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-09-16 23:10:16.0505103 +0200 CEST m=+12.959206201
// using data from
// https://wiki.teamfortress.com/wiki/sniper_responses
package responses

var sniperResponses = []Response{
	
	{
		Class: SNIPER,
		Response: " Mongrel!",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/1f/Sniper_specialcompleted13.wav",
		Context: "Kill with Primary weapon",
		Condition: "Regular",
	},
	
	{
		Class: SNIPER,
		Response: " Bloody bogan!",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/56/Sniper_taunts02.wav",
		Context: "Kill with Primary weapon",
		Condition: "Regular",
	},
	
	{
		Class: SNIPER,
		Response: " You bloody pikers!",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/bb/Sniper_taunts08.wav",
		Context: "Kill with Primary weapon",
		Condition: "Regular",
	},
	
	{
		Class: SNIPER,
		Response: " You're all a bunch of no-hopers!",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/1f/Sniper_taunts09.wav",
		Context: "Kill with Primary weapon",
		Condition: "Regular",
	},
	
	{
		Class: SNIPER,
		Response: " All your heads look bloody twelve feet tall.",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/5e/Sniper_taunts10.wav",
		Context: "Kill with Primary weapon",
		Condition: "Regular",
	},
	
	{
		Class: SNIPER,
		Response: " I'm gonna blow the inside of ya head all over four counties!",
		AudioFile: "https://wiki.teamfortress.com/w/images/e/e5/Sniper_taunts13.wav",
		Context: "Kill with Primary weapon",
		Condition: "Regular",
	},
	
	{
		Class: SNIPER,
		Response: " I'm gunnin' for ya, you mongrels!",
		AudioFile: "https://wiki.teamfortress.com/w/images/6/6d/Sniper_taunts14.wav",
		Context: "Kill with Primary weapon",
		Condition: "Regular",
	},
	
	{
		Class: SNIPER,
		Response: " This is gonna be a real piece of piss, you bloody fruit shop owners!",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/17/Sniper_taunts17.wav",
		Context: "Kill with Primary weapon",
		Condition: "Regular",
	},
	
	{
		Class: SNIPER,
		Response: " I'm gonna turn ya into colored rain!",
		AudioFile: "https://wiki.teamfortress.com/w/images/b/b2/Sniper_taunts19.wav",
		Context: "Kill with Primary weapon",
		Condition: "Regular",
	},
	
	{
		Class: SNIPER,
		Response: " Everything above your neck is going to be a fine red mist!",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/aa/Sniper_taunts22.wav",
		Context: "Kill with Primary weapon",
		Condition: "Regular",
	},
	
	{
		Class: SNIPER,
		Response: " Hold still!",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/f8/Sniper_taunts45.wav",
		Context: "Kill with Primary weapon",
		Condition: "Regular",
	},
	
	{
		Class: SNIPER,
		Response: " Now that was a proper bloody rootin' (whispering)",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/07/Sniper_specialcompleted44.wav",
		Context: "Kill with Primary weapon",
		Condition: "While Scoped",
	},
	
	{
		Class: SNIPER,
		Response: " Bloody bogan. (whispering)",
		AudioFile: "https://wiki.teamfortress.com/w/images/3/3c/Sniper_taunts24.wav",
		Context: "Kill with Primary weapon",
		Condition: "While Scoped",
	},
	
	{
		Class: SNIPER,
		Response: " You big-head wankers. (whispering)",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/15/Sniper_taunts27.wav",
		Context: "Kill with Primary weapon",
		Condition: "While Scoped",
	},
	
	{
		Class: SNIPER,
		Response: " You prancin' show ponies. (whispering)",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/54/Sniper_taunts28.wav",
		Context: "Kill with Primary weapon",
		Condition: "While Scoped",
	},
	
	{
		Class: SNIPER,
		Response: " D'they make them shirts for men? (whispering)",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/4b/Sniper_taunts29.wav",
		Context: "Kill with Primary weapon",
		Condition: "While Scoped",
	},
	
	{
		Class: SNIPER,
		Response: " You bloody pikers. (whispering)",
		AudioFile: "https://wiki.teamfortress.com/w/images/0/09/Sniper_taunts30.wav",
		Context: "Kill with Primary weapon",
		Condition: "While Scoped",
	},
	
	{
		Class: SNIPER,
		Response: " You're all a bunch of no-hopers. (whispering)",
		AudioFile: "https://wiki.teamfortress.com/w/images/a/ac/Sniper_taunts31.wav",
		Context: "Kill with Primary weapon",
		Condition: "While Scoped",
	},
	
	{
		Class: SNIPER,
		Response: " Piss off, you mongrels. (whispering)",
		AudioFile: "https://wiki.teamfortress.com/w/images/5/59/Sniper_taunts37.wav",
		Context: "Kill with Primary weapon",
		Condition: "While Scoped",
	},
	
	{
		Class: SNIPER,
		Response: " Piss off, you bloody pikers. (whispering)",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/1e/Sniper_taunts38.wav",
		Context: "Kill with Primary weapon",
		Condition: "While Scoped",
	},
	
	{
		Class: SNIPER,
		Response: " This is gonna be a real piece of piss, you bloody fruit shop owners. (whispering)",
		AudioFile: "https://wiki.teamfortress.com/w/images/3/34/Sniper_taunts39.wav",
		Context: "Kill with Primary weapon",
		Condition: "While Scoped",
	},
	
}
