// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-09-16 23:10:06.7860832 +0200 CEST m=+3.694779101
// using data from
// https://wiki.teamfortress.com/wiki/soldier_responses
package responses

var soldierResponses = []Response{
	
	{
		Class: SOLDIER,
		Response: "Ka-boom!",
		AudioFile: "https://wiki.teamfortress.com/w/images/1/12/Soldier_specialcompleted03.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with a Primary Weapon",
		Condition: "",
	},
	
	{
		Class: SOLDIER,
		Response: "Maggots!",
		AudioFile: "https://wiki.teamfortress.com/w/images/9/97/Soldier_taunts01.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with a Primary Weapon",
		Condition: "",
	},
	
	{
		Class: SOLDIER,
		Response: "Take your lumps like a man, Private Twinkletoes.",
		AudioFile: "https://wiki.teamfortress.com/w/images/7/79/Soldier_taunts09.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with a Primary Weapon",
		Condition: "",
	},
	
	{
		Class: SOLDIER,
		Response: "You are all weak.  You are all bleeders.",
		AudioFile: "https://wiki.teamfortress.com/w/images/f/ff/Soldier_taunts10.wav",
		Context: "After Killing More than 1 Enemy in 20 Seconds with a Primary Weapon",
		Condition: "",
	},
	
}
