// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-09-16 23:10:17.7537613 +0200 CEST m=+14.662457201
// using data from
// https://wiki.teamfortress.com/wiki/spy_responses
package responses

var spyResponses = []Response{
	
	{
		Class: SPY,
		Response: "Evil laugh",
		AudioFile: "https://wiki.teamfortress.com/w/images/2/2f/Spy_laughevil01.wav",
		Context: "After Killing More than 1 enemy in 20 Seconds with a Secondary Weapon",
		Condition: "",
	},
	
	{
		Class: SPY,
		Response: "Evil laugh 2",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/cf/Spy_laughevil02.wav",
		Context: "After Killing More than 1 enemy in 20 Seconds with a Secondary Weapon",
		Condition: "",
	},
	
	{
		Class: SPY,
		Response: "Happy laugh",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/4f/Spy_laughhappy01.wav",
		Context: "After Killing More than 1 enemy in 20 Seconds with a Secondary Weapon",
		Condition: "",
	},
	
	{
		Class: SPY,
		Response: "Happy laugh 2",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/cd/Spy_laughhappy02.wav",
		Context: "After Killing More than 1 enemy in 20 Seconds with a Secondary Weapon",
		Condition: "",
	},
	
	{
		Class: SPY,
		Response: "Happy laugh 3",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/cc/Spy_laughhappy03.wav",
		Context: "After Killing More than 1 enemy in 20 Seconds with a Secondary Weapon",
		Condition: "",
	},
	
	{
		Class: SPY,
		Response: "Long laugh",
		AudioFile: "https://wiki.teamfortress.com/w/images/c/cd/Spy_laughlong01.wav",
		Context: "After Killing More than 1 enemy in 20 Seconds with a Secondary Weapon",
		Condition: "",
	},
	
	{
		Class: SPY,
		Response: "Short laugh",
		AudioFile: "https://wiki.teamfortress.com/w/images/4/42/Spy_laughshort06.wav",
		Context: "After Killing More than 1 enemy in 20 Seconds with a Secondary Weapon",
		Condition: "",
	},
	
	{
		Class: SPY,
		Response: "Coward!",
		AudioFile: "https://wiki.teamfortress.com/w/images/3/31/Spy_specialcompleted09.wav",
		Context: "After Killing More than 1 enemy in 20 Seconds with a Secondary Weapon",
		Condition: "",
	},
	
	{
		Class: SPY,
		Response: "You disgust me!",
		AudioFile: "https://wiki.teamfortress.com/w/images/8/8a/Spy_specialcompleted10.wav",
		Context: "After Killing More than 1 enemy in 20 Seconds with a Secondary Weapon",
		Condition: "",
	},
	
}
